### ISSUE TITLE
make secret file structure

### ISSUE THREAD

**Issue by bugbounted** [Phaust94/insta_to_tg#1]
Hi [Phaust94](https://github.com/Phaust94),
please make secret credentional struecture or sample on main root repository,
waiting for your commit , 
finest regards

**Comment by Phaust94** [comment]
Hey @pmbeman !
Thanks for showing interest in this little project of mine.
I added some documentation to the README file, along with the secret file structure,  in https://github.com/Phaust94/insta_to_tg/commit/f94a228b8b1fc8d39769d2bef287d011ec6a6fbc
Please feel free to ask if anything is unclear.
